# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-cards',
                'doc_host': 'https://omdgit.github.io',
                'git_url': 'https://github.com/omdgit/nbdev-cards',
                'lib_path': 'nbdev-cards'},
  'syms': { 'nbdev-cards.card': { 'nbdev-cards.card.Card': ('card.html#card', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__gt__': ('card.html#card.__gt__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__init__': ('card.html#card.__init__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__lt__': ('card.html#card.__lt__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__str__': ('card.html#card.__str__', 'nbdev-cards/card.py')},
            'nbdev-cards.deck': { 'nbdev-cards.deck.Deck': ('deck.html#deck', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdev-cards/deck.py')}}}
